# Generated by Django 2.2.10 on 2020-08-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.CharField(max_length=128)),
                ('temparature', models.CharField(max_length=128)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
